name: Spellcheck with codespell

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Commit / Branch / Tag / SHA to checkout
        required: false
        default: ""
      python-version:
        description: Python version
        required: false
        default: "3.x"
  workflow_call:
    inputs:
      tag:
        description: Commit / Branch / Tag / SHA to checkout
        required: false
        default: ""
        type: string
      python-version:
        description: Python version
        required: false
        default: "3.x"
        type: string

permissions:
  contents: read

jobs:
  codespell:
    uses: bagofseeds/actions/.github/workflows/lint.yaml@main
    with:
      tag: ${{ inputs.tag }}
      python-version: ${{ inputs.python-version }}
      requirements-file: requirements-lint.txt
      pip-install: codespell
      lint-command: codespell .
